// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.ProductAPI.DbContexts;

#nullable disable

namespace Services.ProductAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230425135127_InitialDatabase")]
    partial class InitialDatabase
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.ProductAPI.Models.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("Bats")
                        .HasColumnType("integer");

                    b.Property<int>("BirthDay")
                        .HasColumnType("integer");

                    b.Property<int>("BirthMonth")
                        .HasColumnType("integer");

                    b.Property<int>("BirthYear")
                        .HasColumnType("integer");

                    b.Property<string>("BirthCity")
                        .HasColumnType("text");

                    b.Property<string>("BirthCountry")
                        .HasColumnType("text");

                    b.Property<string>("DdRefId")
                        .HasColumnType("text");

                    b.Property<string>("DeathCity")
                        .HasColumnType("text");

                    b.Property<string>("DeathCountry")
                        .HasColumnType("text");

                    b.Property<int>("DeathDay")
                        .HasColumnType("integer");

                    b.Property<int>("DeathMonth")
                        .HasColumnType("integer");

                    b.Property<string>("DeathState")
                        .HasColumnType("text");

                    b.Property<int>("DeathYear")
                        .HasColumnType("integer");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FinalGame")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameFirst")
                        .HasColumnType("text");

                    b.Property<string>("NameGiven")
                        .HasColumnType("text");

                    b.Property<string>("NameLast")
                        .HasColumnType("text");

                    b.Property<string>("RetroId")
                        .HasColumnType("text");

                    b.Property<string>("BirthState")
                        .HasColumnType("text");

                    b.Property<int>("Throws")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("player");
                });
#pragma warning restore 612, 618
        }
    }
}
