// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Services.PlayerAPI.DbContexts;

#nullable disable

namespace Services.PlayerAPI.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20230427144354_init")]
    partial class init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.5")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Services.PlayerAPI.Models.BirthStatusAdditionalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("BirthStatusAdditionalData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("4df64da7-c2cd-4192-b15e-44d27bbfbd41"),
                            City = "a",
                            Country = "b",
                            Day = 1,
                            Month = 2,
                            PlayerId = "aa",
                            State = "1",
                            Year = 2000,
                            status = 0
                        });
                });

            modelBuilder.Entity("Services.PlayerAPI.Models.DeathStatusAdditionalData", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("City")
                        .HasColumnType("text");

                    b.Property<string>("Country")
                        .HasColumnType("text");

                    b.Property<int>("Day")
                        .HasColumnType("integer");

                    b.Property<int>("Month")
                        .HasColumnType("integer");

                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<string>("State")
                        .HasColumnType("text");

                    b.Property<int>("Year")
                        .HasColumnType("integer");

                    b.Property<int>("status")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("PlayerId")
                        .IsUnique();

                    b.ToTable("DeathStatusAdditionalData");

                    b.HasData(
                        new
                        {
                            Id = new Guid("2c61bb88-d982-4860-94de-46d8b5c09228"),
                            City = "a",
                            Country = "b",
                            Day = 1,
                            Month = 2,
                            PlayerId = "aa",
                            State = "1",
                            Year = 2000,
                            status = 0
                        });
                });

            modelBuilder.Entity("Services.PlayerAPI.Models.Player", b =>
                {
                    b.Property<string>("PlayerId")
                        .HasColumnType("text");

                    b.Property<int>("Bats")
                        .HasColumnType("integer");

                    b.Property<string>("DdRefId")
                        .HasColumnType("text");

                    b.Property<DateTime>("Debut")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FinalGame")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NameFirst")
                        .HasColumnType("text");

                    b.Property<string>("NameGiven")
                        .HasColumnType("text");

                    b.Property<string>("NameLast")
                        .HasColumnType("text");

                    b.Property<string>("RetroId")
                        .HasColumnType("text");

                    b.Property<int>("Throws")
                        .HasColumnType("integer");

                    b.Property<int>("Weight")
                        .HasColumnType("integer");

                    b.HasKey("PlayerId");

                    b.ToTable("player");

                    b.HasData(
                        new
                        {
                            PlayerId = "aa",
                            Bats = 1,
                            DdRefId = "123",
                            Debut = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            FinalGame = new DateTime(1, 1, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            NameFirst = "aa",
                            NameGiven = "aa",
                            NameLast = "aa",
                            RetroId = "123",
                            Throws = 1,
                            Weight = 130
                        });
                });

            modelBuilder.Entity("Services.PlayerAPI.Models.BirthStatusAdditionalData", b =>
                {
                    b.HasOne("Services.PlayerAPI.Models.Player", null)
                        .WithOne("BirthStatusAdditionalData")
                        .HasForeignKey("Services.PlayerAPI.Models.BirthStatusAdditionalData", "PlayerId");
                });

            modelBuilder.Entity("Services.PlayerAPI.Models.DeathStatusAdditionalData", b =>
                {
                    b.HasOne("Services.PlayerAPI.Models.Player", null)
                        .WithOne("DeathStatusAdditionalData")
                        .HasForeignKey("Services.PlayerAPI.Models.DeathStatusAdditionalData", "PlayerId");
                });

            modelBuilder.Entity("Services.PlayerAPI.Models.Player", b =>
                {
                    b.Navigation("BirthStatusAdditionalData");

                    b.Navigation("DeathStatusAdditionalData");
                });
#pragma warning restore 612, 618
        }
    }
}
